modLoader = "javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/Tropicraft/Tropicraft/issues"
license = "Mozilla Public License Version 2.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Tropicraft"
displayURL = "https://tropicraft.net"
logoFile = "logo.png"
credits = "Mr_okushama, MrRube, newthead, pablomittens, fotoply, and others who have contributed over the years <3"
authors = "Cojomax99, Corosus, tterrag"
description = '''
This is Tropicraft, the utopian idyllic getaway that you have been waiting for! Craft a pina colada, plop yourself down into a beach chair, take a sip at sunset, and drift away'''

[[mixins]]
config = "tropicraft.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
